// example/nav.vue
<template>
    <div v-classnames="[]">
        <!-- nav__item -->
        <div v-classnames="['item']">item1</div>
        <!-- nav__item nav__item--diabled -->
        <div
            v-classnames="[
                'item',
                {
                    disabled: true,
                },
            ]"
        >
            item2
        </div>
    </div>
</template>

<script lang="ts">
import generateBemClassNames from "bem-classnames/lib/vue";
// step 1: global options
const bemClassNames = generateBemClassNames();
// step 2: register local directives
export default {
    data() {
        return {};
    },
    directives: {
        classnames: bemClassNames("nav"),
    },
    methods: {},
};
</script>

<style lang="scss" >
.nav {
    &__item {
        color: red;
        &--disabled {
            color: blue;
            opacity: 0.1;
        }
    }
}
</style>

// example/nav.jsx
import React from 'react';
import generateClassNames from '../dist/lib/jsx';

// Not using anything
const NavWithNothing = (props) => {
	return (
		<nav className='nav'>
			<ul className='nav__container'>
				<li className='nav__item'></li>
				<li className='nav__item'></li>
				<li className='nav__item nav__item--disabled'></li>
				<li className='nav__item nav__item--active'></li>
			</ul>
		</nav>
	);
};

// step1: global options
const bemClassNames = generateClassNames({
	debug: true,
});
// step2: local
const bem = bemClassNames('nav');
const NavWithBem = (props) => {
	return (
		<nav className={bem()}>
			<ul className={bem('container')}>
				<li className={bem('item')}></li>
				<li className={bem('item')}></li>
				<li className={bem('item', 'disabled')}></li>
				<li className={bem('item', 'active')}></li>
			</ul>
		</nav>
	);
};
